### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by icastillejogomez** [intrinio/javascript-sdk#8]
If you read Standardized Financials docs, you see that one response field is next_page, it is logic if response has some pages, but in parameters doc section (in JS SDK too) next_page parameter is not documented. 

The point is: Standardized Financials method can responses with two or more pages?

Thanks!!

**Comment by civilframe** [comment]
Hi @icastillejogomez ! We are working on cleaning up various issues in the docs. For Standardized Financials, you can expect all possible records to be returned in the first page, there will never be a second page. Thanks!
